site_name: Heavens Above
site_url: https://nishazafran.github.io/heavens-above/

plugins:
  - search

nav:
  - Home: index.md
  - New Doc: newdoc.md
  - New Page: newpage.md

theme:
  name: material

