site_name: Heavens Above
site_url: https://nishazafran.github.io/heavens-above/

plugins:
  - search
  - awesome-pages

nav:
  - Home: index.md
  - New Doc: newdoc.md
  - New Page: newpage.md
  - Test Page: testpage.md

theme:
  name: material
